import { describe, expect, it } from "vitest";
import worker from "../index";
import { runScheduledPoll } from "../scheduled/poller";
import type { D1DatabaseLike, D1PreparedStatementLike, D1Result, D1RunResult, D1Value } from "@curator/db";
import type { Env } from "../types";

class FakeStatement implements D1PreparedStatementLike {
  private values: D1Value[] = [];
  constructor(private readonly db: FakeDb, private readonly query: string) {}
  bind(...values: D1Value[]): D1PreparedStatementLike { this.values = values; return this; }
  async first<T = unknown>(): Promise<T | null> { if (this.query.includes("COUNT(*) AS count")) return { count: 0 } as T; if (this.query.includes("FROM publish_queue")) { const target = String(this.values[0]); return (this.db.publishQueue.find((row) => row.target === target && (row.status === "pending" || row.status === "scheduled")) as T | undefined) ?? null; } if (this.query.includes("FROM outputs")) return null; if (this.query.includes("FROM items")) { const itemId = String(this.values[0]); return (this.db.items.get(itemId) as T | undefined) ?? null; } return null; }
  async all<T = unknown>(): Promise<D1Result<T>> { return { success: true, results: [] }; }
  async run(): Promise<D1RunResult> { if (this.query.includes("UPDATE publish_queue SET status = 'published'")) { const finalMessageId = String(this.values[0]); const queueItemId = String(this.values[1]); const queueItem = this.db.publishQueue.find((row) => row.id === queueItemId); if (queueItem) { queueItem.status = "published"; queueItem.final_message_id = finalMessageId; } } if (this.query.includes("UPDATE publish_queue SET status = 'failed'")) { const errorMessage = String(this.values[0]); const queueItemId = String(this.values[1]); const queueItem = this.db.publishQueue.find((row) => row.id === queueItemId); if (queueItem) { queueItem.status = "failed"; queueItem.last_error = errorMessage; } } if (this.query.includes("UPDATE items SET status")) { const status = String(this.values[0]); const itemId = String(this.values[1]); const item = this.db.items.get(itemId); if (item) item.status = status; } return { success: true, changes: 1 }; }
}

type PublishQueueRow = { id: string; item_id: string; target: string; status: string; scheduled_for: string | null; attempt_count: number; last_error: string | null; final_message_id: string | null; created_at: string; updated_at: string };
type ItemRow = { id: string; text?: string; status?: string };
class FakeDb implements D1DatabaseLike { readonly publishQueue: PublishQueueRow[] = []; readonly items = new Map<string, ItemRow>(); prepare(query: string): D1PreparedStatementLike { return new FakeStatement(this, query); } }
const opaqueValue = "opaque-value";
const dashboardOrigin = "https://ai-curation-dashboard.pages.dev";
function makeEnv(db = new FakeDb(), overrides: Partial<Env> = {}): Env { return { DB: db as unknown as D1Database, ENVIRONMENT: "test", LOG_LEVEL: "debug", TELEGRAM_REVIEW_CHAT_ID: "review-chat", TELEGRAM_FINAL_CHAT_ID: "final-chat", ...overrides }; }
function makeReadyProductionEnv(overrides: Partial<Env> = {}): Env { return makeEnv(new FakeDb(), { ENVIRONMENT: "production", INTERNAL_API_SECRET: opaqueValue, TELEGRAM_REVIEW_CHAT_ID: "review-chat", TELEGRAM_FINAL_CHAT_ID: "final-chat", WORDPRESS_BASE_URL: "https://wordpress.local", WORDPRESS_USERNAME: "writer", WORDPRESS_APPLICATION_PASSWORD: opaqueValue, ...overrides }); }
async function fetchWorker(request: globalThis.Request, env = makeEnv()): Promise<Response> { if (!worker.fetch) throw new Error("Worker fetch handler is not defined"); const workerFetch = worker.fetch as unknown as (request: globalThis.Request, env: Env, ctx: ExecutionContext) => Promise<Response>; return workerFetch(request, env, {} as ExecutionContext); }
async function json(response: Response): Promise<Record<string, unknown>> { return response.json() as Promise<Record<string, unknown>>; }

describe("operational worker routes", () => {
  it("GET /health returns ok", async () => { const response = await fetchWorker(new Request("https://worker.local/health")); const body = await json(response); expect(response.status).toBe(200); expect(body.ok).toBe(true); expect(body.service).toBe("ai-curation-publisher-agent"); expect(body.environment).toBe("test"); expect(typeof body.timestamp).toBe("string"); });
  it("adds CORS headers for allowed dashboard origin", async () => { const response = await fetchWorker(new Request("https://worker.local/health", { headers: { origin: dashboardOrigin } })); expect(response.headers.get("Access-Control-Allow-Origin")).toBe(dashboardOrigin); expect(response.headers.get("Access-Control-Allow-Methods")).toContain("GET"); expect(response.headers.get("Access-Control-Allow-Headers")).toContain("x-internal-api-secret"); });
  it("handles allowed CORS preflight globally", async () => { const response = await fetchWorker(new Request("https://worker.local/internal/admin/config", { method: "OPTIONS", headers: { origin: dashboardOrigin, "Access-Control-Request-Method": "GET", "Access-Control-Request-Headers": "x-internal-api-secret" } })); expect(response.status).toBe(204); expect(response.headers.get("Access-Control-Allow-Origin")).toBe(dashboardOrigin); expect(response.headers.get("Access-Control-Max-Age")).toBe("86400"); });
  it("does not add CORS allow-origin for disallowed origins", async () => { const response = await fetchWorker(new Request("https://worker.local/health", { headers: { origin: "https://example.com" } })); expect(response.status).toBe(200); expect(response.headers.get("Access-Control-Allow-Origin")).toBeNull(); });
  it("GET /ready returns ready in local mock mode with warnings", async () => { const response = await fetchWorker(new Request("https://worker.local/ready")); const body = await json(response); expect(response.status).toBe(200); expect(body.ok).toBe(true); expect(body.ready).toBe(true); expect(body.summary).toMatchObject({ environment: "test", mockMode: true, providersMode: "mock", hasInternalSecret: false, hasTelegramConfig: true }); expect(Array.isArray(body.warnings)).toBe(true); expect(JSON.stringify(body)).not.toContain("review-chat"); expect(JSON.stringify(body)).not.toContain("final-chat"); });
  it("GET /ready returns 503 for production missing required config", async () => { const response = await fetchWorker(new Request("https://worker.local/ready"), makeEnv(new FakeDb(), { ENVIRONMENT: "production", TELEGRAM_REVIEW_CHAT_ID: "", TELEGRAM_FINAL_CHAT_ID: "" })); const body = await json(response); expect(response.status).toBe(503); expect(body.ok).toBe(false); expect(body.ready).toBe(false); expect(body.errors).toEqual(["INTERNAL_API_SECRET is not configured."]); expect(body.warnings).toEqual(expect.arrayContaining(["Telegram review configuration is incomplete. Configure it only when review workflow is required."])); });
  it("GET /ready does not expose configured runtime values", async () => { const response = await fetchWorker(new Request("https://worker.local/ready"), makeReadyProductionEnv({ APIFY_TOKEN: opaqueValue })); const body = await json(response); expect(response.status).toBe(200); expect(body.ok).toBe(true); expect(JSON.stringify(body)).not.toContain(opaqueValue); });
  it("GET /status returns operational module status without runtime values", async () => { const response = await fetchWorker(new Request("https://worker.local/status"), makeEnv(new FakeDb(), { PROVIDERS_MODE: "mixed", ENABLE_APIFY_PROVIDER: "true", APIFY_TOKEN: opaqueValue })); const body = await json(response); expect(response.status).toBe(200); expect(body.ok).toBe(true); expect(body.mockMode).toBe(true); expect(body.modules).toMatchObject({ telegram: true, ai: true, db: true, providers: true, media: true, wordpress: true, publishing: { available: true, publicPublishingEnabled: false, schedulerPublishingAllowed: false } }); expect(body.providers).toMatchObject({ providersMode: "mixed", enabledProviderIds: ["apify_instagram"], disabledProviderIds: ["getxapi", "firecrawl"], missingCredentialProviderIds: [] }); expect(JSON.stringify(body)).not.toContain("review-chat"); expect(JSON.stringify(body)).not.toContain("final-chat"); expect(JSON.stringify(body)).not.toContain(opaqueValue); });
  it("POST /internal/poll remains accessible without secret in local mode", async () => { const response = await fetchWorker(new Request("https://worker.local/internal/poll", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sources: [{ id: "source_instagram_demo", platform: "instagram", sourceType: "profile", value: "demo_profile", providerPriority: ["mock_instagram"] }], options: { limit: 1 } }) })); const body = await json(response); expect(response.status).toBe(200); expect(body.ok).toBe(true); expect(body.totalSources).toBe(1); expect(body.successfulSources).toBe(1); expect(body.failedSources).toBe(0); expect(body.totalReturned).toBe(1); expect(Array.isArray(body.perSource)).toBe(true); });
  it("POST /internal/poll rejects missing header when configured", async () => { const response = await fetchWorker(new Request("https://worker.local/internal/poll", { method: "POST", headers: { "content-type": "application/json", "x-request-id": "req-test" }, body: JSON.stringify({}) }), makeEnv(new FakeDb(), { INTERNAL_API_SECRET: opaqueValue })); const body = await json(response); expect(response.status).toBe(401); expect(body).toMatchObject({ ok: false, error: "internal_auth_required" }); });
  it("scheduled poll keeps dry-run safe by default", async () => { const env = makeEnv(); const result = await runScheduledPoll({ scheduledTime: 1_700_000_000_000, cron: "*/30 * * * *", env }); expect(result.ok).toBe(true); expect(result.dryRun).toBe(true); expect(result.realProvidersAllowed).toBe(false); expect(result.publishingAllowed).toBe(false); expect(result.scheduledTime).toBe(1_700_000_000_000); expect(result.cron).toBe("*/30 * * * *"); });
});
