-- Phase 1 initial D1 schema.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS sources (id TEXT PRIMARY KEY, platform TEXT NOT NULL, source_type TEXT NOT NULL, value TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', provider_priority_json TEXT NOT NULL DEFAULT '[]', last_seen_post_id TEXT, last_seen_at TEXT, provider_cursor TEXT, last_successful_poll_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS items (id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES sources(id) ON DELETE CASCADE, provider TEXT NOT NULL, platform TEXT NOT NULL, source_type TEXT NOT NULL, source_post_id TEXT, canonical_url TEXT NOT NULL, canonical_url_hash TEXT NOT NULL, normalized_text_hash TEXT, status TEXT NOT NULL, published_at TEXT, author_handle TEXT, text TEXT, links_json TEXT NOT NULL DEFAULT '[]', raw_payload_json TEXT NOT NULL DEFAULT '{}', error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_items_source_status ON items(source_id, status);
CREATE INDEX IF NOT EXISTS idx_items_status_created_at ON items(status, created_at);
CREATE INDEX IF NOT EXISTS idx_items_canonical_url_hash ON items(canonical_url_hash);
CREATE TABLE IF NOT EXISTS dedupe_keys (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, key_type TEXT NOT NULL, key_value TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(key_type, key_value));
CREATE TABLE IF NOT EXISTS media_assets (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, kind TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', source_url TEXT NOT NULL, canonical_url TEXT, media_url_hash TEXT, r2_key TEXT, public_url TEXT, size_bytes INTEGER, mime_type TEXT, width INTEGER, height INTEGER, duration_seconds REAL, error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS prompts (id TEXT PRIMARY KEY, name TEXT NOT NULL, target TEXT NOT NULL, version TEXT NOT NULL, template TEXT NOT NULL, is_active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(name, version));
CREATE TABLE IF NOT EXISTS outputs (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, target TEXT NOT NULL, prompt_id TEXT REFERENCES prompts(id), prompt_version TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', output_json TEXT NOT NULL DEFAULT '{}', input_tokens INTEGER, output_tokens INTEGER, estimated_cost_usd REAL, error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(item_id, target, prompt_version));
CREATE TABLE IF NOT EXISTS review_messages (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, telegram_chat_id TEXT NOT NULL, telegram_message_id TEXT NOT NULL, review_status TEXT NOT NULL DEFAULT 'sent', edited_caption TEXT, sent_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(telegram_chat_id, telegram_message_id));
CREATE TABLE IF NOT EXISTS publish_queue (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, target TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', scheduled_for TEXT, attempt_count INTEGER NOT NULL DEFAULT 0, last_error TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS wordpress_posts (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, wordpress_post_id TEXT, wordpress_url TEXT, status TEXT NOT NULL DEFAULT 'draft', title TEXT, slug TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(item_id));
CREATE TABLE IF NOT EXISTS provider_logs (id TEXT PRIMARY KEY, provider TEXT NOT NULL, platform TEXT NOT NULL, source_id TEXT REFERENCES sources(id) ON DELETE SET NULL, status TEXT NOT NULL, request_json TEXT NOT NULL DEFAULT '{}', response_count INTEGER NOT NULL DEFAULT 0, error_message TEXT, duration_ms INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS review_actions (id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE, reviewer_id TEXT NOT NULL, action TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, description TEXT, is_secret INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
