import type { ApiResult, JsonObject, JsonValue, RuntimeChecklistItem, SetupCenterModel, SetupDetailItem, SetupStatus, StatusBundle } from "./types";

export type RiskLabel = "Safe" | "Warning" | "Risky";

type StatusData = { healthOk: boolean; statusOk: boolean; readyOk: boolean; status: JsonObject; readySummary: JsonObject };

export function deriveSetupCenter(bundle: StatusBundle, hasLocalInternalCredential: boolean): SetupCenterModel {
  const data = readStatusData(bundle);
  const workerReachable = data.healthOk && data.statusOk;
  const backendHasInternalSecret = readBoolean(data.readySummary, ["hasInternalSecret"]);
  const scheduler = deriveSchedulerSafety(bundle);
  const telegramReady = readBoolean(data.readySummary, ["productionReviewReady"]) === true || readBoolean(data.readySummary, ["hasTelegramConfig"]) === true;
  const wordpressReady = readBoolean(data.readySummary, ["wordpressDraftReady"]) === true || readBoolean(data.readySummary, ["hasWordPressConfig"]) === true;
  const firecrawlReady = readBoolean(data.readySummary, ["hasProviderCredentials", "firecrawl"]) === true && readBoolean(data.status, ["providers", "firecrawl", "enabled"]) === true;
  const pilotReady = readBoolean(data.status, ["pilot", "ready"]) === true;
  const riskyConfig = scheduler.riskLabel === "Risky";
  const readinessIncomplete = workerReachable && !data.readyOk;

  return {
    workerConnection: status(workerReachable, "Worker reachable", "Worker connection needs attention", workerReachable ? "The dashboard can reach the deployed Worker. Launch readiness is checked separately." : "Set the Worker API base URL, then refresh status.", workerReachable ? "Continue to readiness checks." : "Enter the deployed Worker URL and check /health and /status."),
    internalSecurity: status(backendHasInternalSecret === true && hasLocalInternalCredential, "Internal routes protected and dashboard credential entered", backendHasInternalSecret === true ? "Backend is protected; dashboard credential is missing" : "Backend internal secret is missing", backendHasInternalSecret === true ? "The Worker reports internal route protection. Enter the value locally to run protected checks." : "Configure INTERNAL_API_SECRET as a Cloudflare Worker Secret before using protected operations.", backendHasInternalSecret === true && hasLocalInternalCredential ? "Run the internal auth check." : "Configure the Worker Secret and enter the same value locally in this browser."),
    cloudflareRuntime: buildRuntimeChecklist(bundle),
    telegram: buildTelegramChecklist(bundle),
    wordpress: buildWordPressChecklist(bundle),
    firecrawl: buildFirecrawlChecklist(bundle),
    scheduler,
    launchSummary: {
      overallStatus: riskyConfig ? "Risky config" : !workerReachable || backendHasInternalSecret !== true ? "Not ready" : pilotReady ? "Pilot-ready" : "Setup in progress",
      workerReachable: workerReachable ? "Ready" : "Needs setup",
      internalSecurity: backendHasInternalSecret === true && hasLocalInternalCredential ? "Ready" : "Needs setup",
      telegramReadiness: telegramReady ? "Ready for review dry-run" : "Optional setup incomplete",
      wordpressReadiness: wordpressReady ? "Ready for draft dry-run" : "Optional setup incomplete",
      firecrawlReadiness: firecrawlReady ? "Ready for sandbox fetch" : "Optional setup incomplete",
      schedulerSafety: scheduler.riskLabel,
      publishingSafety: scheduler.publishingAllowed === true ? "Risky" : "Safe",
      recommendedNextStep: readinessIncomplete ? "Worker is online. Continue fixing readiness warnings instead of changing the Worker URL." : chooseLaunchNextStep({ workerReachable, backendHasInternalSecret, hasLocalInternalCredential, riskyConfig, telegramReady, wordpressReady, firecrawlReady })
    }
  };
}

export function deriveSchedulerSafety(bundle: StatusBundle): SetupCenterModel["scheduler"] {
  const data = readStatusData(bundle);
  const scheduler = readObject(data.readySummary, ["scheduler"]) ?? readObject(data.status, ["scheduler"]) ?? {};
  const quotas = readObject(data.readySummary, ["quotas"]) ?? readObject(data.status, ["quotas"]) ?? {};
  const enabled = readBoolean(scheduler, ["enabled"]);
  const dryRun = readBoolean(scheduler, ["dryRun"]);
  const realProvidersAllowed = readBoolean(scheduler, ["realProvidersAllowed"]);
  const publishingAllowed = readBoolean(scheduler, ["publishingAllowed"]);
  const maxSourcesPerRun = readNumber(scheduler, ["maxSourcesPerRun"]);
  const maxItemsPerRun = readNumber(scheduler, ["maxItemsPerRun"]);
  const maxAiItemsPerRun = readNumber(quotas, ["maxAiItemsPerRun"]);
  const maxProviderItemsPerRun = readNumber(quotas, ["maxProviderItemsPerRun"]);
  const maxPublishItemsPerRun = readNumber(quotas, ["maxPublishItemsPerRun"]);
  const warnings: string[] = [];
  if (enabled === true) warnings.push("Scheduler is enabled. Confirm this is intentional before launch.");
  if (dryRun === false) warnings.push("Scheduler dry-run is off. This is not safe for setup mode.");
  if (realProvidersAllowed === true) warnings.push("Scheduler can use real providers. Keep this disabled for setup.");
  if (publishingAllowed === true) warnings.push("Scheduler publishing is allowed. This is risky before launch approval.");
  const riskLabel: RiskLabel = publishingAllowed === true || realProvidersAllowed === true || dryRun === false ? "Risky" : enabled === true ? "Warning" : "Safe";
  return { riskLabel, ...(enabled === undefined ? {} : { enabled }), ...(dryRun === undefined ? {} : { dryRun }), ...(realProvidersAllowed === undefined ? {} : { realProvidersAllowed }), ...(publishingAllowed === undefined ? {} : { publishingAllowed }), ...(maxSourcesPerRun === undefined ? {} : { maxSourcesPerRun }), ...(maxItemsPerRun === undefined ? {} : { maxItemsPerRun }), ...(maxAiItemsPerRun === undefined ? {} : { maxAiItemsPerRun }), ...(maxProviderItemsPerRun === undefined ? {} : { maxProviderItemsPerRun }), ...(maxPublishItemsPerRun === undefined ? {} : { maxPublishItemsPerRun }), warnings };
}

export function buildManagerSetupSummary(bundle: StatusBundle, hasLocalInternalCredential: boolean): SetupCenterModel["launchSummary"] { return deriveSetupCenter(bundle, hasLocalInternalCredential).launchSummary; }
export function redactSensitiveJson(value: JsonValue): JsonValue { if (Array.isArray(value)) return value.map((entry) => redactSensitiveJson(entry)); if (!isRecord(value)) return typeof value === "string" ? redactSensitiveText(value) : value; const next: JsonObject = {}; for (const [key, nested] of Object.entries(value)) next[key] = isSensitiveKey(key) ? "[redacted]" : redactSensitiveJson(nested); return next; }
export function redactSensitiveText(value: string): string { return value.replace(/(secret|token|password|credential)(["'\s:=]+)[^\s,}"']+/gi, "$1$2[redacted]"); }

function buildRuntimeChecklist(bundle: StatusBundle): RuntimeChecklistItem[] { const data = readStatusData(bundle); const scheduler = readObject(data.readySummary, ["scheduler"]) ?? readObject(data.status, ["scheduler"]) ?? {}; const quotas = readObject(data.readySummary, ["quotas"]) ?? readObject(data.status, ["quotas"]) ?? {}; return [item("ENVIRONMENT", "Identifies the Worker environment.", "Cloudflare Worker Variable", false, readString(data.readySummary, ["environment"]), "production"), item("LOG_LEVEL", "Controls how much the Worker logs.", "Cloudflare Worker Variable", false, readString(data.status, ["logLevel"]), "info"), item("PROVIDERS_MODE", "Keeps content providers in mock mode unless explicitly piloted.", "Cloudflare Worker Variable", false, readString(data.readySummary, ["providersMode"]), "mock"), item("SCHEDULER_ENABLED", "Controls scheduled background runs.", "Cloudflare Worker Variable", false, boolValue(readBoolean(scheduler, ["enabled"])), "false"), item("SCHEDULER_DRY_RUN", "Keeps scheduler checks from doing real work.", "Cloudflare Worker Variable", false, boolValue(readBoolean(scheduler, ["dryRun"])), "true"), item("SCHEDULER_ALLOW_REAL_PROVIDERS", "Prevents scheduled real provider polling.", "Cloudflare Worker Variable", false, boolValue(readBoolean(scheduler, ["realProvidersAllowed"])), "false"), item("SCHEDULER_ALLOW_PUBLISHING", "Prevents scheduler publishing.", "Cloudflare Worker Variable", false, boolValue(readBoolean(scheduler, ["publishingAllowed"])), "false"), item("SCHEDULER_MAX_SOURCES_PER_RUN", "Limits scheduler source count.", "Cloudflare Worker Variable", false, numberValue(readNumber(scheduler, ["maxSourcesPerRun"])), "1"), item("SCHEDULER_MAX_ITEMS_PER_RUN", "Limits scheduler item count.", "Cloudflare Worker Variable", false, numberValue(readNumber(scheduler, ["maxItemsPerRun"])), "2"), item("MAX_AI_ITEMS_PER_RUN", "Limits AI work during setup.", "Cloudflare Worker Variable", false, numberValue(readNumber(quotas, ["maxAiItemsPerRun"])), "0"), item("MAX_PROVIDER_ITEMS_PER_RUN", "Limits provider item processing.", "Cloudflare Worker Variable", false, numberValue(readNumber(quotas, ["maxProviderItemsPerRun"])), "5"), item("MAX_PUBLISH_ITEMS_PER_RUN", "Keeps publishing disabled during setup.", "Cloudflare Worker Variable", false, numberValue(readNumber(quotas, ["maxPublishItemsPerRun"])), "0"), item("TELEGRAM_REAL_REVIEW_ENABLED", "Allows review-channel dry-run only when intentionally enabled.", "Cloudflare Worker Variable", false, boolValue(readBoolean(data.readySummary, ["telegramRealReviewEnabled"])), "false"), item("WORDPRESS_REAL_DRY_RUN_ENABLED", "Allows WordPress draft dry-run only when intentionally enabled.", "Cloudflare Worker Variable", false, boolValue(readBoolean(data.readySummary, ["wordpressRealDryRunEnabled"])), "false"), item("WORDPRESS_DEFAULT_STATUS", "Keeps WordPress output as draft.", "Cloudflare Worker Variable", false, readString(data.readySummary, ["wordpressDefaultStatus"]), "draft")]; }
function buildTelegramChecklist(bundle: StatusBundle): SetupDetailItem[] { const data = readStatusData(bundle); const statusTelegram = readObject(data.status, ["telegram"]) ?? {}; return [detail("TELEGRAM_BOT_TOKEN", "Bot credential used only by the Worker to contact Telegram.", "Cloudflare Worker Secret", true, readBoolean(data.readySummary, ["hasTelegramBotToken"]) ?? readBoolean(statusTelegram, ["botTokenConfigured"]), "Create a bot with BotFather, then store the token as a Worker Secret. Do not paste it into the dashboard."), detail("TELEGRAM_WEBHOOK_SECRET", "Optional shared value that verifies Telegram webhook calls.", "Cloudflare Worker Secret", true, undefined, "Generate a random value and store it as a Worker Secret if webhook verification is used."), detail("TELEGRAM_REVIEW_CHAT_ID", "Private review destination where draft messages are sent.", "Cloudflare Worker Secret or Variable", true, readBoolean(statusTelegram, ["reviewChatConfigured"]), "Send a message to the review chat, then use Telegram getUpdates or a trusted local tool to identify the chat ID without exposing the bot token."), detail("TELEGRAM_FINAL_CHAT_ID", "Final channel destination. It stays unused by dashboard setup checks.", "Cloudflare Worker Secret or Variable", true, readBoolean(statusTelegram, ["finalChatConfigured"]), "Configure only when final publishing is intentionally approved. The dashboard does not publish to final Telegram."), detail("TELEGRAM_REAL_REVIEW_ENABLED", "Allows review-channel dry-run after everything is configured.", "Cloudflare Worker Variable", false, readBoolean(data.readySummary, ["telegramRealReviewEnabled"]) ?? readBoolean(statusTelegram, ["realReviewEnabled"]), "Keep false until you intentionally run review-channel dry-run.")]; }
function buildWordPressChecklist(bundle: StatusBundle): SetupDetailItem[] { const data = readStatusData(bundle); return [detail("WORDPRESS_BASE_URL", "WordPress site URL used by the Worker.", "Cloudflare Worker Variable or Secret", true, readBoolean(data.readySummary, ["hasWordPressBaseUrl"]), "Set the site URL only when draft dry-run is needed."), detail("WORDPRESS_USERNAME", "WordPress REST username.", "Cloudflare Worker Secret", true, readBoolean(data.readySummary, ["hasWordPressCredentials"]), "Store as a Worker Secret or controlled runtime value. Do not show it in the dashboard."), detail("WORDPRESS_APPLICATION_PASSWORD", "WordPress application password for REST draft creation.", "Cloudflare Worker Secret", true, readBoolean(data.readySummary, ["hasWordPressCredentials"]), "Create it in WordPress and store it as a Worker Secret."), detail("WORDPRESS_DEFAULT_STATUS", "Target WordPress post status.", "Cloudflare Worker Variable", false, readString(data.readySummary, ["wordpressDefaultStatus"]), "Use draft for setup and pilot checks."), detail("WORDPRESS_REAL_DRY_RUN_ENABLED", "Allows explicit WordPress draft dry-run.", "Cloudflare Worker Variable", false, readBoolean(data.readySummary, ["wordpressRealDryRunEnabled"]), "Keep disabled until you intentionally test draft creation.")]; }
function buildFirecrawlChecklist(bundle: StatusBundle): SetupDetailItem[] { const data = readStatusData(bundle); const firecrawl = readObject(data.status, ["providers", "firecrawl"]) ?? {}; return [detail("PROVIDERS_MODE", "Provider mode. Setup should stay mock unless intentionally piloting.", "Cloudflare Worker Variable", false, readString(data.readySummary, ["providersMode"]), "Keep mock by default. Use mixed only for controlled provider pilot."), detail("ENABLE_FIRECRAWL_PROVIDER", "Enables Firecrawl sandbox provider inside the Worker.", "Cloudflare Worker Variable", false, readBoolean(firecrawl, ["enabled"]), "Do not enable from the dashboard. Configure manually only for a scoped pilot."), detail("FIRECRAWL_API_KEY", "Credential used by the Worker for Firecrawl sandbox fetch.", "Cloudflare Worker Secret", true, readBoolean(data.readySummary, ["hasProviderCredentials", "firecrawl"]) ?? readBoolean(firecrawl, ["configured"]), "Store as a Worker Secret. Never paste it into the dashboard."), detail("FIRECRAWL_BASE_URL", "Optional Firecrawl endpoint override.", "Cloudflare Worker Variable", false, undefined, "Leave default unless you intentionally use a sandbox endpoint."), detail("FIRECRAWL_TIMEOUT_MS", "Timeout for Firecrawl sandbox requests.", "Cloudflare Worker Variable", false, undefined, "Keep conservative to avoid long or costly runs.")]; }
function status(ok: boolean, okLabel: string, badLabel: string, detailText: string, nextAction: string): SetupStatus { return { label: ok ? okLabel : badLabel, tone: ok ? "safe" : "warning", detail: detailText, nextAction }; }
function item(name: string, purpose: string, where: string, sensitive: boolean, backendValue: string | undefined, safeDefault: string): RuntimeChecklistItem { const matchesSafeDefault = backendValue === safeDefault; return { name, purpose, where, sensitive, safeDefault, backendStatus: backendValue === undefined ? "Not reported" : backendValue, ...(backendValue === undefined ? {} : { safe: matchesSafeDefault }), nextAction: matchesSafeDefault ? "No action needed." : "Check this value in Cloudflare Worker Variables." }; }
function detail(name: string, purpose: string, where: string, sensitive: boolean, configuredOrValue: boolean | string | undefined, nextAction: string): SetupDetailItem { const currentStatus = typeof configuredOrValue === "boolean" ? configuredOrValue ? "Configured" : "Missing" : typeof configuredOrValue === "string" ? configuredOrValue : "Manual check"; return { name, purpose, where, sensitive, currentStatus, nextAction }; }
function chooseLaunchNextStep(input: { workerReachable: boolean; backendHasInternalSecret: boolean | undefined; hasLocalInternalCredential: boolean; riskyConfig: boolean; telegramReady: boolean; wordpressReady: boolean; firecrawlReady: boolean }): string { if (!input.workerReachable) return "Connect the Worker API URL and refresh status."; if (input.backendHasInternalSecret !== true) return "Configure INTERNAL_API_SECRET in Cloudflare Worker Secrets."; if (!input.hasLocalInternalCredential) return "Enter the internal credential locally in this browser to unlock protected setup checks."; if (input.riskyConfig) return "Fix scheduler or publishing risk before any pilot step."; if (!input.telegramReady && !input.wordpressReady && !input.firecrawlReady) return "Choose one optional integration to configure manually, or run readiness-only pilot first."; return "Run mock E2E, then one explicit pilot step at a time."; }
function readStatusData(bundle: StatusBundle): StatusData { const statusData = asObject(bundle.status); const readyData = asObject(bundle.ready); return { healthOk: bundle.health?.ok === true, statusOk: bundle.status?.ok === true, readyOk: bundle.ready?.ok === true, status: statusData, readySummary: readObject(readyData, ["summary"]) ?? readObject(statusData, ["readiness"]) ?? {} }; }
function asObject(result: ApiResult | undefined): JsonObject { return result?.ok === true && isRecord(result.data) ? result.data : {}; }
function readObject(value: JsonObject, path: string[]): JsonObject | undefined { const nested = readPath(value, path); return isRecord(nested) ? nested : undefined; }
function readBoolean(value: JsonObject, path: string[]): boolean | undefined { const nested = readPath(value, path); return typeof nested === "boolean" ? nested : undefined; }
function readString(value: JsonObject, path: string[]): string | undefined { const nested = readPath(value, path); return typeof nested === "string" ? nested : undefined; }
function readNumber(value: JsonObject, path: string[]): number | undefined { const nested = readPath(value, path); return typeof nested === "number" ? nested : undefined; }
function readPath(value: JsonObject, path: string[]): unknown { let current: unknown = value; for (const key of path) { if (!isRecord(current)) return undefined; current = current[key]; } return current; }
function isRecord(value: unknown): value is JsonObject { return typeof value === "object" && value !== null && !Array.isArray(value); }
function isSensitiveKey(key: string): boolean { const normalized = key.toLowerCase(); return normalized.includes("token") || normalized.includes("secret") || normalized.includes("password") || normalized.includes("credential") || normalized.includes("authorization"); }
function boolValue(value: boolean | undefined): string | undefined { return value === undefined ? undefined : value ? "true" : "false"; }
function numberValue(value: number | undefined): string | undefined { return value === undefined ? undefined : String(value); }
